# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('n1', models.IntegerField(default=1)),
                ('n2', models.IntegerField(default=1)),
                ('n3', models.IntegerField(default=1)),
                ('n4', models.IntegerField(default=1)),
                ('n5', models.IntegerField(default=1)),
                ('powb', models.IntegerField(default=1)),
            ],
        ),
    ]
